# Generated by Django 2.1.10 on 2019-08-13 16:10

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernorm',
            name='test',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
            migrations.AddField(
            model_name='activity',
            name='typeof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ActivityType'),
        ),
    ]
